# Dockerfile.serving
FROM python:3.11-slim

WORKDIR /app

COPY requirements_serving.txt .
RUN pip install --no-cache-dir -r requirements_serving.txt

# Copy API
COPY api_server.py .

# Create model directory
RUN mkdir -p /app/model

# Copy artifacts dynamically
COPY federated_data/federated_churn_model.h5 /app/model/
COPY federated_data/preprocessor.pkl /app/model/

EXPOSE 8000

CMD ["uvicorn", "api_server:app", "--host", "0.0.0.0", "--port", "8000"]
