# Dockerfile.training
FROM tensorflow/tensorflow:2.14.0

WORKDIR /app

# Copy only necessary files
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY prepare_federated_data.py .
COPY federated_training.py .
COPY evaluate_federated_model.py .
COPY E_Commerce_Dataset.xlsx .

# Environment variable for MLflow tracking
ENV MLFLOW_TRACKING_URI=http://mlflow:5000

CMD ["python", "federated_training.py"]


