FROM python:3.11-slim

WORKDIR /app

COPY requirements_serving.txt .
RUN pip install --no-cache-dir -r requirements_serving.txt

COPY federated_data/federated_churn_model.h5 ./model/
COPY federated_data/preprocessor.pkl ./model/
COPY api_server.py .

EXPOSE 8000

CMD ["uvicorn", "api_server:app", "--host", "0.0.0.0", "--port", "8000"]